version: "3.4"

services:
  prometheus-web:
    image: prom/prometheus:latest
    #network_mode: "host"
    restart: on-failure
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    #network_mode: "host"
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    #network_mode: "host"
    restart: unless-stopped
    ports:
      - "9999:3000"
    user: "0"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost:9999

