apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe -f .\docker-compose.k8s.yml convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: wf-backend
  name: wf-backend
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3000
  selector:
    io.kompose.service: wf-backend
  type: LoadBalancer
status:
  loadBalancer: {}
