export const sortable = ["id", "name", "jpName", "engname", "businessScope"];
export const searchable = ["name", "jpName", "enName"];
export const fillable = [
    "name",
    "jpName",
    "enName",
    "companyStatus",
    "equityStatus",
    "capitalAmount",
    "totalPaidinCapital",
    "shareValue",
    "equityAmount",
    "registrationAuthority",
    "registrationDate",
    "lastModificationDate",
    "specialVotingRights",
    "specificIssuesVeto",
    "specialShareholderRight",
    "businessScope",
    "zipCode",
    "address",
    "tel",
    "fax",
    "taxIdNumber",
    "site",
    "representName",
    "representTitle",
    "email",
    "contactName",
    "remark",
    "createdUser",
    "updatedUser",
    "createdAt",
    "updatedAt"
];
